spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accommodation_db
    driver-class-name: org.postgresql.Driver
    username: booking
    password: booking1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: accommodation-booking-service
      auto-offset-reset: earliest
    producer:
      acks: all
